# Generated by Django 3.2.7 on 2021-10-02 11:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('site_admin', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer_report',
            name='temporary_buddies',
            field=models.ManyToManyField(blank=True, related_name='vol_temp_buddies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='volunteer_report',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='volunteer_attendance_report', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='volunteer_profile',
            name='available_day_time_slots',
            field=models.ManyToManyField(blank=True, related_name='volunteer_preferred_schedule', to='site_admin.Session_Day_Time'),
        ),
        migrations.AddField(
            model_name='volunteer_profile',
            name='gender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='volunteer_gender', to='site_admin.gender'),
        ),
        migrations.AddField(
            model_name='volunteer_profile',
            name='mega',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vol_mega_team', to='site_admin.mega_team'),
        ),
        migrations.AddField(
            model_name='volunteer_profile',
            name='primary_lang',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vol_primary_lang', to='site_admin.language'),
        ),
        migrations.AddField(
            model_name='volunteer_profile',
            name='profile_notes',
            field=models.ManyToManyField(blank=True, related_name='volunteer_profile_notes', to='site_admin.Note'),
        ),
        migrations.AddField(
            model_name='volunteer_profile',
            name='scheduled_day_time_slots',
            field=models.ManyToManyField(blank=True, related_name='volunteer_scheduled_slots', to='site_admin.Session_Day_Time'),
        ),
        migrations.AddField(
            model_name='volunteer_profile',
            name='secondary_lang',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vol_secondary_lang', to='site_admin.language'),
        ),
        migrations.AddField(
            model_name='volunteer_profile',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vol_team', to='site_admin.team'),
        ),
        migrations.AddField(
            model_name='volunteer_profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='volunteer_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user_log',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room_name', to='site_admin.room', verbose_name='Jitsi Room'),
        ),
        migrations.AddField(
            model_name='user_log',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='team_meeting',
            name='day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_admin.day'),
        ),
        migrations.AddField(
            model_name='team_meeting',
            name='team',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='meeting', to='site_admin.team'),
        ),
        migrations.AddField(
            model_name='team',
            name='leader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_leader', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='team',
            name='meeting_day',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_meeting_day', to='site_admin.day'),
        ),
        migrations.AddField(
            model_name='team',
            name='mega',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mega_team', to='site_admin.mega_team'),
        ),
        migrations.AddField(
            model_name='team',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_room', to='site_admin.room'),
        ),
        migrations.AddField(
            model_name='team',
            name='volunteers',
            field=models.ManyToManyField(blank=True, related_name='team_vols', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='student_report',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_semester_report', to='site_admin.semester'),
        ),
        migrations.AddField(
            model_name='student_report',
            name='sessions_scheduled',
            field=models.ManyToManyField(blank=True, related_name='student_scheduled_sessions', to='site_admin.Daily_Session'),
        ),
        migrations.AddField(
            model_name='student_report',
            name='temporary_buddies',
            field=models.ManyToManyField(blank=True, related_name='student_temp_buddies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='student_report',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_attendance_report', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='student_progress',
            name='current',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_level', to='site_admin.reading_level'),
        ),
        migrations.AddField(
            model_name='student_progress',
            name='end',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='end_level', to='site_admin.reading_level'),
        ),
        migrations.AddField(
            model_name='student_progress',
            name='level_progress',
            field=models.ManyToManyField(blank=True, related_name='reading_progress', to='site_admin.Session_Reading_Level'),
        ),
        migrations.AddField(
            model_name='student_progress',
            name='progress_notes',
            field=models.ManyToManyField(blank=True, related_name='student_progress_notes', to='site_admin.Note'),
        ),
        migrations.AddField(
            model_name='student_progress',
            name='starting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='start_level', to='site_admin.reading_level'),
        ),
        migrations.AddField(
            model_name='student_progress',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_progress', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='student_profile',
            name='available_day_time_slots',
            field=models.ManyToManyField(blank=True, related_name='student_preferred_schedule', to='site_admin.Session_Day_Time'),
        ),
        migrations.AddField(
            model_name='student_profile',
            name='gender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_gender', to='site_admin.gender'),
        ),
        migrations.AddField(
            model_name='student_profile',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_grade', to='site_admin.grade'),
        ),
        migrations.AddField(
            model_name='student_profile',
            name='primary_lang',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_primary_lang', to='site_admin.language'),
        ),
        migrations.AddField(
            model_name='student_profile',
            name='profile_notes',
            field=models.ManyToManyField(blank=True, related_name='student_profile_notes', to='site_admin.Note'),
        ),
        migrations.AddField(
            model_name='student_profile',
            name='scheduled_day_time_slots',
            field=models.ManyToManyField(blank=True, related_name='student_scheduled_slots', to='site_admin.Session_Day_Time'),
        ),
        migrations.AddField(
            model_name='student_profile',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_school', to='site_admin.school'),
        ),
        migrations.AddField(
            model_name='student_profile',
            name='secondary_lang',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_secondary_lang', to='site_admin.language'),
        ),
        migrations.AddField(
            model_name='student_profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='staff_profile',
            name='gender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_gender', to='site_admin.gender'),
        ),
        migrations.AddField(
            model_name='staff_profile',
            name='mega',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_mega_team', to='site_admin.mega_team'),
        ),
        migrations.AddField(
            model_name='staff_profile',
            name='primary_lang',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_primary_lang', to='site_admin.language'),
        ),
        migrations.AddField(
            model_name='staff_profile',
            name='profile_notes',
            field=models.ManyToManyField(blank=True, related_name='staff_profile_notes', to='site_admin.Note'),
        ),
        migrations.AddField(
            model_name='staff_profile',
            name='secondary_lang',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_secondary_lang', to='site_admin.language'),
        ),
        migrations.AddField(
            model_name='staff_profile',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_team', to='site_admin.team'),
        ),
        migrations.AddField(
            model_name='staff_profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sign_in_by_day',
            name='day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_with_session', to='site_admin.day_with_daily_session'),
        ),
        migrations.AddField(
            model_name='sign_in_by_day',
            name='logs',
            field=models.ManyToManyField(blank=True, related_name='user_log', to='site_admin.User_Log'),
        ),
        migrations.AddField(
            model_name='sign_in_by_day',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sch_session', to='site_admin.daily_session'),
        ),
        migrations.AddField(
            model_name='sign_in_by_day',
            name='session_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slot', to='site_admin.session_day_time'),
        ),
        migrations.AddField(
            model_name='sign_in_by_day',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='session_time_status', to='site_admin.attendance_status'),
        ),
        migrations.AddField(
            model_name='sign_in_by_day',
            name='temporary_buddies',
            field=models.ManyToManyField(blank=True, related_name='user_temp_buddies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sign_in_by_day',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sign_ins', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='session_reading_level',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='today_level', to='site_admin.reading_level'),
        ),
        migrations.AddField(
            model_name='session_reading_level',
            name='level_notes',
            field=models.ManyToManyField(blank=True, related_name='session_level_notes', to='site_admin.Note'),
        ),
        migrations.AddField(
            model_name='session_reading_level',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='session_rl', to='site_admin.daily_session'),
        ),
        migrations.AddField(
            model_name='session_reading_level',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_by_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='session_reading_level',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_rl', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='session_day_time',
            name='day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_admin.day'),
        ),
        migrations.AddField(
            model_name='semester',
            name='day_time_slots',
            field=models.ManyToManyField(blank=True, related_name='semester_slots', to='site_admin.Session_Day_Time'),
        ),
        migrations.AddField(
            model_name='semester',
            name='days',
            field=models.ManyToManyField(blank=True, related_name='days_in_session', to='site_admin.Day'),
        ),
        migrations.AddField(
            model_name='room',
            name='jitsi_participants',
            field=models.ManyToManyField(blank=True, related_name='jitsi_participants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='room',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='room_participants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='room',
            name='room_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='type_room', to='site_admin.room_type', verbose_name='Room Type'),
        ),
        migrations.AddField(
            model_name='note_category',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='note_group', to='site_admin.note_group'),
        ),
        migrations.AddField(
            model_name='note',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='made_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='note',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes_category', to='site_admin.note_category'),
        ),
        migrations.AddField(
            model_name='mega_team',
            name='coordinator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mega_coordinator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mega_team',
            name='team_leaders',
            field=models.ManyToManyField(blank=True, related_name='mega_team_leaders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mega_team',
            name='volunteers',
            field=models.ManyToManyField(blank=True, related_name='mega_team_vol', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='day_with_team_meeting',
            name='day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_admin.day'),
        ),
        migrations.AddField(
            model_name='day_with_team_meeting',
            name='day_meetings',
            field=models.ManyToManyField(blank=True, related_name='day_meetings', to='site_admin.Team_Meeting'),
        ),
        migrations.AddField(
            model_name='day_with_team_meeting',
            name='semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='semester_meetings', to='site_admin.semester'),
        ),
        migrations.AddField(
            model_name='day_with_orientation_meeting',
            name='allowed_participants',
            field=models.ManyToManyField(blank=True, related_name='orientation_allowed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='day_with_daily_session',
            name='day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_admin.day'),
        ),
        migrations.AddField(
            model_name='day_with_daily_session',
            name='day_sessions',
            field=models.ManyToManyField(blank=True, related_name='day_sessions', to='site_admin.Daily_Session'),
        ),
        migrations.AddField(
            model_name='day_with_daily_session',
            name='semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='semester_day', to='site_admin.semester'),
        ),
        migrations.AddField(
            model_name='daily_session',
            name='day_time',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='session_day_time', to='site_admin.session_day_time'),
        ),
        migrations.AddField(
            model_name='daily_session',
            name='semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_sessions', to='site_admin.semester'),
        ),
    ]
