# Generated by Django 3.2.7 on 2021-10-02 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_admin', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='daily_session',
            name='student_entry_allowed_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='daily_session',
            name='student_entry_allowed_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
