# Generated by Django 3.2.6 on 2021-10-13 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_admin', '0003_auto_20211002_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='server_time',
            name='days',
            field=models.ManyToManyField(blank=True, related_name='server_days', to='site_admin.Day'),
        ),
    ]
