# Generated by Django 3.2.6 on 2021-10-19 10:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('site_admin', '0004_server_time_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_progress',
            name='end_assessment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student_progress',
            name='half_assessment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student_progress',
            name='initial_assessment',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Student_Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='last updated')),
                ('assessed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='performed_by', to=settings.AUTH_USER_MODEL)),
                ('level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_level', to='site_admin.reading_level')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student Assessment',
                'verbose_name_plural': 'Student Assessments',
                'ordering': ['user'],
            },
        ),
        migrations.AddField(
            model_name='student_progress',
            name='assessments',
            field=models.ManyToManyField(blank=True, related_name='reading_assessments', to='site_admin.Student_Assessment'),
        ),
    ]
