# Generated by Django 3.2.6 on 2021-11-18 09:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('site_admin', '0006_student_progress_last_assessed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sign_In_By_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_sign_ins', models.IntegerField(blank=True, null=True)),
                ('total_minutes', models.IntegerField(blank=True, default=0, null=True)),
                ('total_hours', models.IntegerField(blank=True, default=0, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='last updated')),
                ('logs', models.ManyToManyField(blank=True, related_name='user_logs', to='site_admin.User_Log')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_sign_ins', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sign In By User',
                'verbose_name_plural': 'Sign Ins By User',
                'ordering': ['user__full_name'],
            },
        ),
    ]
