# Generated by Django 3.2.6 on 2021-11-19 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_admin', '0008_auto_20211118_0606'),
    ]

    operations = [
        migrations.AddField(
            model_name='sign_in_by_user',
            name='logs_4_8',
            field=models.ManyToManyField(blank=True, related_name='user_logs_4_8', to='site_admin.User_Log'),
        ),
        migrations.AddField(
            model_name='sign_in_by_user',
            name='total_hours_4_8',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='sign_in_by_user',
            name='total_minutes_4_8',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='sign_in_by_user',
            name='total_sign_ins_4_8',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
