# Generated by Django 3.2.6 on 2021-11-19 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_admin', '0010_auto_20211119_0645'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_log',
            name='day_good',
            field=models.BooleanField(default=False),
        ),
    ]
