# Generated by Django 3.2.6 on 2021-11-19 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_admin', '0011_user_log_day_good'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_log',
            name='day_of_week',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
