# Generated by Django 3.2.6 on 2021-11-19 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_admin', '0012_user_log_day_of_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_log',
            name='complete_log',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user_log',
            name='count_in_total',
            field=models.BooleanField(default=False),
        ),
    ]
