# Generated by Django 3.2.6 on 2021-11-20 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_admin', '0015_auto_20211120_0810'),
    ]

    operations = [
        migrations.AddField(
            model_name='sign_in_by_user',
            name='missing_out_good_day',
            field=models.BooleanField(default=False),
        ),
    ]
