# Generated by Django 3.2.6 on 2021-11-20 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_admin', '0016_sign_in_by_user_missing_out_good_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='sign_in_by_user',
            name='missing_time_good_logs',
            field=models.ManyToManyField(blank=True, related_name='logs_missing_time_good_day', to='site_admin.User_Log'),
        ),
        migrations.AddField(
            model_name='sign_in_by_user',
            name='missing_time_logs',
            field=models.ManyToManyField(blank=True, related_name='logs_missing_time', to='site_admin.User_Log'),
        ),
    ]
