# Generated by Django 3.2.6 on 2021-11-20 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_admin', '0017_auto_20211120_0848'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_log',
            name='needs_attention',
            field=models.BooleanField(default=False),
        ),
    ]
