# Generated by Django 3.2.6 on 2021-11-21 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_admin', '0019_sign_in_by_user_explore_user_logs'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_log',
            name='room_good',
            field=models.BooleanField(default=False),
        ),
    ]
