# Generated by Django 3.2.6 on 2021-11-21 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_admin', '0020_user_log_room_good'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_log',
            name='processed_all_good',
            field=models.BooleanField(default=False),
        ),
    ]
