# Generated by Django 3.2.6 on 2021-11-21 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_admin', '0021_user_log_processed_all_good'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_log',
            old_name='processed_all_good',
            new_name='processed_completely',
        ),
    ]
