# Generated by Django 3.2.6 on 2021-11-21 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_admin', '0022_rename_processed_all_good_user_log_processed_completely'),
    ]

    operations = [
        migrations.AddField(
            model_name='server_time',
            name='student_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='server_time',
            name='student_start',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
