# Generated by Django 3.2.6 on 2021-11-21 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_admin', '0025_auto_20211121_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='sign_in_by_user',
            name='total_hours_good',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='sign_in_by_user',
            name='total_minutes_good',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
