# Generated by Django 3.2.6 on 2021-11-22 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_admin', '0026_auto_20211121_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_log',
            name='manually_added',
            field=models.BooleanField(default=False),
        ),
    ]
