# Generated by Django 3.2.7 on 2021-10-02 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reading_sessions', '0001_initial'),
        ('site_admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_session_status',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room_location', to='site_admin.room'),
        ),
    ]
