# Generated by Django 3.2.7 on 2021-10-02 11:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('site_admin', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reading_sessions', '0002_user_session_status_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_session_status',
            name='scheduled_buddy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sch_buddy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user_session_status',
            name='scheduled_match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sch_match', to='reading_sessions.scheduled_match'),
        ),
        migrations.AddField(
            model_name='user_session_status',
            name='temp_match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='temp_match', to='reading_sessions.temporary_match'),
        ),
        migrations.AddField(
            model_name='user_session_status',
            name='temporary_buddy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temp_buddy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user_session_status',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='session_status', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='temporary_match',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temp_match', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='temporary_match',
            name='notes',
            field=models.ManyToManyField(blank=True, related_name='temporary_match_notes', to='site_admin.Note'),
        ),
        migrations.AddField(
            model_name='temporary_match',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temporary_match_session', to='site_admin.daily_session'),
        ),
        migrations.AddField(
            model_name='temporary_match',
            name='student_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_temp_match', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='temporary_match',
            name='teacher_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_temp_match', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='temporary_match',
            name='temp_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temp_type_match', to='reading_sessions.temporary_match_type'),
        ),
        migrations.AddField(
            model_name='scheduled_match',
            name='notes',
            field=models.ManyToManyField(blank=True, related_name='scheduled_match_notes', to='site_admin.Note'),
        ),
        migrations.AddField(
            model_name='scheduled_match',
            name='scheduled_slots',
            field=models.ManyToManyField(blank=True, related_name='match_slots', to='site_admin.Session_Day_Time'),
        ),
        migrations.AddField(
            model_name='scheduled_match',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_match_semester', to='site_admin.semester'),
        ),
        migrations.AddField(
            model_name='scheduled_match',
            name='sessions_scheduled',
            field=models.ManyToManyField(blank=True, related_name='scheduled_matches_in_session', to='site_admin.Daily_Session'),
        ),
        migrations.AddField(
            model_name='scheduled_match',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_student', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scheduled_match',
            name='volunteer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_volunteer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='match_status',
            name='match_status_notes',
            field=models.ManyToManyField(blank=True, related_name='match_status_notes', to='site_admin.Note'),
        ),
        migrations.AddField(
            model_name='match_status',
            name='match_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match_status_type', to='reading_sessions.match_type'),
        ),
        migrations.AddField(
            model_name='match_status',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match_location', to='site_admin.room'),
        ),
        migrations.AddField(
            model_name='match_status',
            name='sch_match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sch_match_status', to='reading_sessions.scheduled_match'),
        ),
        migrations.AddField(
            model_name='match_status',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match_status_session', to='site_admin.daily_session'),
        ),
        migrations.AddField(
            model_name='match_status',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='status_option', to='reading_sessions.match_status_option'),
        ),
        migrations.AddField(
            model_name='match_status',
            name='temp_match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temp_match_status', to='reading_sessions.temporary_match'),
        ),
        migrations.AddField(
            model_name='match_attendance_record',
            name='match_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match_attendance_type', to='reading_sessions.match_type'),
        ),
        migrations.AddField(
            model_name='match_attendance_record',
            name='notes',
            field=models.ManyToManyField(blank=True, related_name='match_attendance_notes', to='site_admin.Note'),
        ),
        migrations.AddField(
            model_name='match_attendance_record',
            name='sch_match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sch_match_attendance_record', to='reading_sessions.scheduled_match'),
        ),
        migrations.AddField(
            model_name='match_attendance_record',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match_attendance_session', to='site_admin.daily_session'),
        ),
        migrations.AddField(
            model_name='match_attendance_record',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='record_status', to='reading_sessions.match_status_option'),
        ),
        migrations.AddField(
            model_name='match_attendance_record',
            name='temp_match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temp_match_attendance_record', to='reading_sessions.temporary_match'),
        ),
        migrations.AddField(
            model_name='end_session_evaluation',
            name='assessment_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assessed_level', to='site_admin.reading_level'),
        ),
        migrations.AddField(
            model_name='end_session_evaluation',
            name='completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_completed_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='end_session_evaluation',
            name='comprehension',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comp', to='reading_sessions.evaluation_level', verbose_name='Comprehension'),
        ),
        migrations.AddField(
            model_name='end_session_evaluation',
            name='engagement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relational_engagemnet', to='reading_sessions.relational_engagement', verbose_name='Relational Engagement'),
        ),
        migrations.AddField(
            model_name='end_session_evaluation',
            name='follow_up_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='type_follow_up', to='reading_sessions.follow_up_type'),
        ),
        migrations.AddField(
            model_name='end_session_evaluation',
            name='level_today',
            field=models.ManyToManyField(blank=True, related_name='session_levels', to='site_admin.Reading_Level'),
        ),
        migrations.AddField(
            model_name='end_session_evaluation',
            name='pronunciation_fluency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pro_flu', to='reading_sessions.evaluation_level', verbose_name='Pronunciation/Fluency'),
        ),
        migrations.AddField(
            model_name='end_session_evaluation',
            name='scheduled_student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evalution_for_scheduled', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='end_session_evaluation',
            name='scheduled_student_attendance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sch_arrival', to='reading_sessions.arrival_description'),
        ),
        migrations.AddField(
            model_name='end_session_evaluation',
            name='tbd',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tbd_unk', to='reading_sessions.evaluation_level', verbose_name='TBD'),
        ),
        migrations.AddField(
            model_name='end_session_evaluation',
            name='temp_student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evalution_for_other', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='end_session_evaluation',
            name='temp_student_attendance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='other_arrival', to='reading_sessions.arrival_description'),
        ),
        migrations.AddField(
            model_name='end_session_evaluation',
            name='vocabulary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='voc', to='reading_sessions.evaluation_level', verbose_name='Vocabulary'),
        ),
        migrations.AddField(
            model_name='end_session_evaluation',
            name='word_recognition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='word_rec', to='reading_sessions.evaluation_level', verbose_name='Word Recognition'),
        ),
        migrations.AddField(
            model_name='connection_drop',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drop_room_location', to='site_admin.room'),
        ),
        migrations.AddField(
            model_name='connection_drop',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drop_status', to=settings.AUTH_USER_MODEL),
        ),
    ]
