# Generated by Django 3.2.7 on 2021-10-05 12:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('site_admin', '0003_auto_20211002_1137'),
        ('reading_sessions', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='API_Jitsi_Room_Participants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occupied', models.BooleanField(default=False)),
                ('api_count', models.IntegerField(default=0, verbose_name='Count')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='last updated')),
                ('participants', models.ManyToManyField(blank=True, related_name='api_room_participants', to=settings.AUTH_USER_MODEL)),
                ('room', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='jitis_room', to='site_admin.room')),
            ],
            options={
                'verbose_name': 'API Room Participants',
                'verbose_name_plural': 'API Room Participants',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='A_Problem_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='last updated')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='problem_location', to='site_admin.room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connection_problem', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'A_Problem_User',
                'verbose_name_plural': 'A_Problem_User',
                'ordering': ['-date_created'],
            },
        ),
    ]
