# Generated by Django 3.2.7 on 2021-10-05 16:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reading_sessions', '0004_a_problem_user_api_jitsi_room_participants'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('online', models.BooleanField(default=False, verbose_name='Online')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='last updated')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='status_ws', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'A_User_Status',
                'verbose_name_plural': 'A_User_Status',
                'ordering': ['-last_updated'],
            },
        ),
    ]
