# Generated by Django 3.2.6 on 2021-10-10 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reading_sessions', '0006_alter_user_status_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='a_problem_user',
            options={'ordering': ['user__username'], 'verbose_name': 'A_Problem_User', 'verbose_name_plural': 'A_Problem_User'},
        ),
    ]
