# Generated by Django 3.2.6 on 2021-10-26 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reading_sessions', '0008_incomplete_evaluation'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_status',
            name='all_connected',
            field=models.BooleanField(default=False, verbose_name='All Connected'),
        ),
        migrations.AddField(
            model_name='user_status',
            name='max_reached',
            field=models.BooleanField(default=False, verbose_name='Max Reached'),
        ),
        migrations.AddField(
            model_name='user_status',
            name='needs_to_reenter',
            field=models.BooleanField(default=False, verbose_name='Needs To Reenter'),
        ),
    ]
