# Generated by Django 3.2.6 on 2021-10-26 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reading_sessions', '0009_auto_20211026_0753'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_status',
            name='has_redirect',
            field=models.BooleanField(default=False, verbose_name='Has Redirect'),
        ),
    ]
