# Generated by Django 3.2.6 on 2021-10-27 12:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('site_admin', '0006_student_progress_last_assessed'),
        ('reading_sessions', '0010_user_status_has_redirect'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_status',
            name='has_redirect',
        ),
        migrations.AddField(
            model_name='user_status',
            name='has_status_redirect',
            field=models.BooleanField(default=False, verbose_name='Status Redirect'),
        ),
        migrations.AddField(
            model_name='user_status',
            name='has_ws_redirect',
            field=models.BooleanField(default=False, verbose_name='WS Redirect'),
        ),
        migrations.CreateModel(
            name='Status_Redirect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_send', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_user', to=settings.AUTH_USER_MODEL)),
                ('to_room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_location', to='site_admin.room')),
                ('user_to_redirect', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='status_redirect', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Status Redirect',
                'verbose_name_plural': 'Status Redirects',
            },
        ),
    ]
