# Generated by Django 3.2.6 on 2021-11-04 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reading_sessions', '0012_user_status_in_room'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='a_problem_user',
            options={'ordering': ['-date_created', 'user__username'], 'verbose_name': 'A_Problem_User', 'verbose_name_plural': 'A_Problem_User'},
        ),
        migrations.AddField(
            model_name='a_problem_user',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
