# Generated by Django 3.2.6 on 2021-10-10 16:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('site_admin', '0003_auto_20211002_1137'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jitsi_User_Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('online', models.BooleanField(default=False, verbose_name='Online')),
                ('time_in', models.DateTimeField(blank=True, null=True)),
                ('time_out', models.DateTimeField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='last updated')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jitsi_room_name', to='site_admin.room', verbose_name='Jitsi Room')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='status_jitsi', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Jitsi User Status',
                'verbose_name_plural': 'Jitsi User Status',
                'ordering': ['user'],
            },
        ),
    ]
