# Generated by Django 3.2.6 on 2021-10-12 12:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_admin', '0003_auto_20211002_1137'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jitsi_data', '0003_auto_20211012_0751'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jitsi_Meeting_Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occupied', models.BooleanField(default=False)),
                ('count', models.IntegerField(default=0, verbose_name='Count')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='last updated')),
                ('participants', models.ManyToManyField(blank=True, related_name='api_participants', to=settings.AUTH_USER_MODEL)),
                ('room', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='room_jitsi', to='site_admin.room')),
            ],
            options={
                'verbose_name': 'Jitsi Meeting Room',
                'verbose_name_plural': 'Jitsi Meeting Rooms',
                'ordering': ['room__id'],
            },
        ),
    ]
