# Generated by Django 3.2.6 on 2021-10-14 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jitsi_data', '0004_jitsi_meeting_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='jitsi_meeting_room',
            name='mismatch',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jitsi_meeting_room',
            name='student_alone',
            field=models.BooleanField(default=False),
        ),
    ]
