# Generated by Django 3.2.6 on 2021-11-01 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_admin', '0006_student_progress_last_assessed'),
        ('jitsi_data', '0005_auto_20211014_0743'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jitsi_user_status',
            name='jitsi_id',
        ),
        migrations.CreateModel(
            name='Jitsi_ID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jitsi_id', models.CharField(blank=True, max_length=255, null=True)),
                ('in_room', models.BooleanField(default=False, verbose_name='In Room')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='last updated')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='id_room_name', to='site_admin.room', verbose_name='Jitsi Room')),
            ],
            options={
                'verbose_name': 'Jitsi ID',
                'verbose_name_plural': 'Jitsi IDs',
                'ordering': ['room'],
            },
        ),
        migrations.AddField(
            model_name='jitsi_user_status',
            name='jitsi_ids',
            field=models.ManyToManyField(blank=True, related_name='ids_jitsi', to='jitsi_data.Jitsi_ID'),
        ),
    ]
